lane :test do
  encrypt_secrets(
    hash_key: "IMPROVE-THIS-SECRET",
    language: "swift",
    secrets_dir_path: "./TestProject/",
    secrets: {
      "google_map_key" => "ABCDEFGHIJKLM",
      "some_api_token" => "AFGDFGDFAJGADFJGAFJ",
    }
  )

  decrypt_secrets(
    file_path: "./TestProject/secrets.gpg",
    target_path: "./TestProject/",
  )
end
